version: "3.1"

services:
  permissions-db:
    image: postgres:16.4
    container_name: permissions_db
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - psql:/var/lib/postgresql/data

volumes:
  psql:
